INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM, CURRENCY_TO, RATE_EXCHANGE) VALUES (1002, 'USD', 'CFA', 609.00);
INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM, CURRENCY_TO, RATE_EXCHANGE) VALUES (1003, 'EUR', 'CFA', 660.67);
INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM, CURRENCY_TO, RATE_EXCHANGE) VALUES (1004, 'DIHRAM', 'CFA', 59.82);
INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM, CURRENCY_TO, RATE_EXCHANGE) VALUES (1005, 'NAIRA', 'CFA', 1.35);